### ISSUE TITLE
Trouble Installing: ros-melodic-ros-base

### ISSUE THREAD

**Issue by santaimpersonator** [dusty-nv/jetbot_ros#11]
I had trouble installing the ROS Melodic from the command line:
`sudo apt-get install ros-melodic-ros-base`

Instead, I followed these [instructions](http://wiki.ros.org/Installation/Ubuntu):
[http://wiki.ros.org/Installation/Ubuntu](http://wiki.ros.org/Installation/Ubuntu)

**Note:** You will need to run the command in section 1.3 to set up your keys before clicking the link in section 1.4.

I hope this helps others.

**Comment by igaki** [comment]
In my case, I faced the following GPG error after executing `sudo apt-get update`.
```
GPG error: http://packages.ros.org/ros/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F42ED6FBAB17C654
```

So, I executed the following commands for gpg before `sudo apt-get update`
```
gpg --keyserver keyserver.ubuntu.com --recv-key F42ED6FBAB17C654
gpg -a --export F42ED6FBAB17C654 | sudo apt-key add -
```

**Comment by red24dog** [comment]
I have 2 further comments:
1: apt update fails/cannot install packages. The cause is described in [https://answers.ros.org/question/325039/apt-update-fails-cannot-install-pkgs-key-not-working/](url). Old keys prior to Jun/2019 were revoked due a security issue. 

# delete old key
sudo apt-key del 421C365BD9FF1F717815A3895523BAEEB01FA116
# add the new key
sudo -E apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654

2: catkin_make error
jetbot@jetbotROS:~$ cd workspace/catkin_ws
jetbot@jetbotROS:~/workspace/catkin_ws$ catkin_make
-bash: catkin_make: command not found.

I fixed the error by installing python-rosinstall, python-rosinstall-generator. python-wstool, as described in the ROS Melodic Installation Wiki. And executing source ~$.bashrc (or ~$..bashrc after installing Melodic executing this command # add ROS paths to environment

Perhaps the installations are not necessary my experience is that the "source" command seems essential after any changes to .bashrc are made.

**Comment by santaimpersonator** [comment]
I'm going to close this issue. It looks like @dusty-nv has since [updated the instructions](https://github.com/dusty-nv/jetbot_ros#install-ros-melodic) to resolve the issue.
